### ISSUE TITLE
works with rpi3?

### ISSUE THREAD

**Issue by ajaygunalan** [yamaguchi-am/kondo-ics#2] opened 2019-02-13 09:36 UTC
Hey, 

I'm trying to get the Kondo KRS6003 to work with my RPI3-3, the code is [here](https://github.com/ajaygunalan/rpi3_loopback_serial/blob/master/ics.c)

To control the KRS 6003, We need to set the Enable Pin **High** and do the transmission and set the enable **Low** for receiving the return value form the servo.

However, I'm not able to keep the enable high without using delay. I wonder how you are doing it?
I couldn't find anything related to enable High and Low in your code. Could you help me on It? 

I know that  ` write ` by default is a **Blocking** function which means until TX transmits, execution  is blocked (which I want). So when I use like below. It doesn't work, enable goes low immediately.
```
enableHigh
write( )
enableLow
```

So I use like this, to have enable low after TX finished transmitting but it causes other problem.

```
enableHigh
write()
delay(3.2);
enableLow

```

**Comment by yamaguchi-am** [comment] 2019-02-15 00:30
Hi,

Sorry not being clear, but the code in this project does not do anything like you mentioned. It is because it's intended to be used with KONDO's USB adapter that wraps the half-duplex comm line as a full-duplex serial port.

From your code, I guessed you are doing something resolved by leveraging the hardware flow control, (or possibly don't need it evenly). I imagine that the serial data is buffered in the hardware which works independently of the other components like GPIO.

However, I think I need to ask you few more information before answer. What exact chips / circuit configuration you are using with the code in your project for connecting to servos?

**Comment by ajaygunalan** [comment] 2019-02-21 06:18
Hey,

Sorry for my late reply. Yeah, you are right. I'm using this Kondo [ICS Converison board](https://kondo-robot.com/product/03121). It works with Arduino ([code](https://github.com/ajaygunalan/kondo/blob/master/kondo.ino)) But when I try to do the same with rpi3, for the same baud rate, the length of the signal varies in TX of rpi3 when compared to Arduino.

My question is would it be possible to control the servo from RPI3, Odroid using ICS conversion board?

**Comment by ajaygunalan** [comment] 2019-03-06 08:11
Hey,

Sorry to bother you. Any update?

**Comment by yamaguchi-am** [comment] 2019-03-06 15:28
If you just need to send commands to KONDO ICS servo motors from Raspberry Pi 3 without any hardware restriction, I would recommend to use DUAL USB ADAPTER https://kondo-robot.com/product/02116 (NOT the ICS conversion board).
Using the adapter on Linux is not supported by the manufacturer, however, I got it work seemingly successfully, on my Linux laptop and Raspbian on RPi1.
So the shortest answer to your question would be yes.

If you need to use ICS Conversion board, I am sorry that I haven't tried yet unfortunately. With a quick survey I could not find a way to know exact timing on RPi when all UART bits are sent out .
However I would like to dump some thoughts in my mind:

Some applications that converts between RS232C and other serial buses utilize the RTS signal of a serial port as a means of switching the bus direction.
For example: http://www.windmill.co.uk/rs485.html
I've found Raspberry Pi's embedded UART has pin output for RTS.
https://ethertubes.com/raspberry-pi-rts-cts-flow-control/
So this was what existed in my mind when I said "leveraging the hardware flow control" before.
Having said that, now I am thinking this approach is still difficult or infeasible in some situation.
This approach require to set up the serial port device to the mode where it asserts RTS while sending data. This is different from modern use of the RTS signal, like seen in the above article on RPi.
Some existing Linux distributions might not support that mode evenly. Although some articles says Windows supports it.
Also see: https://www.tldp.org/HOWTO/Serial-HOWTO-19.html#ss19.4

Another possible approach is making a circuit that turns the serial port into an open-drain driver like this:
https://github.com/lipoyang/ICSlib
But it may not be able to communicate with the devices at the full speed. When I tried before, it could only work at 115200bps. I also think it'd limit the number of servos or the total length of the cables.

**Comment by ajaygunalan** [comment] 2019-03-07 07:59
Thank you for your reply. I have faced the same problem of, 

> exact timing on RPi when all UART bits are sent out

I used Blocking UART functions from POSIX, `write`. But, Not able to match timing requirements.

So, I moved on to the Embedded Platform. But, Do you think Real Time Programming on RPI3 would solve it?

**Comment by yamaguchi-am** [comment] 2021-12-31 08:39
To close the loop, the required function must be done by the device driver layer (or even the electronic circuit layer using the RTS signal mentioned in my previous comment), rather than user program like this library or a "real time programming", in principle.
The KONDO USB ICS adapter or Raspberry pi serial port provides a device like /dev/ttyS0 and making it accessible by write/read system calls. It hides everything other than reading or writing bytes; it may do buffering, wait until device is ready, or switching bus direction for half-duplex. So the layers above it, by design, cannot control those things like the bus direction control in sync with the bit transmission.

**Closed as completed by yamaguchi-am** 2021-12-31 08:39 UTC
